# Aditya Ketanbhai Shah – G01449892
# Suhas Thandaga Ramesh – G01450932
# Niharika FNU LNU – G01412073
# Syedfurkhan Feroz Hashmi – G01411748
# Use a base image. Here, we use nginx as a web server.
FROM nginx:alpine

# Copy your HTML form into the container's file system
COPY index.html /usr/share/nginx/html
